### ISSUE TITLE
Proper titlecasing

### ISSUE THREAD

**Issue by christoomey** [christoomey/vim-titlecase#2]
- Capitalize the first word
- Capitalize all hyphenated words
- Don't capitalize words of 3 letters or less
- Never capitalize thoughtbot
- Don't capitalize after apostrophes
- Don't alter capitalization of all caps words, e.g. `HTML`

http://blog.apastyle.org/apastyle/2012/03/title-case-and-sentence-case-capitalization-in-apa-style.html
http://grammar.about.com/od/grammarfaq/f/capitalstitle.htm
https://github.com/gouch/to-title-case/blob/master/to-title-case.js

**Comment by toomey8** [comment]
+1 on this - just logged on to see if this was possible. Seems like your would also not want to titlecase CamelCase and function.calls. 

thanks for a great plugin.

**Comment by chenoweth** [comment]
> Don't capitalize words of 3 letters or less

It could be done by adding adding the multi `{3,}` inside the 2nd captured group of the regex matching a word to capitalize.

Currently it's:

    let WORD_PATTERN = '\v<(\k)(\k*)>'

It could be replaced by:

    let WORD_PATTERN = '\v''@<!&<(\k)(\k{3,})>'

The part before the `&` is a concat to make sure the word is not after an apostrophe.

> Don't alter capitalization of all caps words, e.g. HTML

It could be done by adding another concat:

    let WORD_PATTERN = '\v%(\k*\u\k+|\k+\u\k*)@!&''@<!&<(\k)(\k{3,})>'

The `%(\k*\u\k+|\k+\u\k*)@!&` part makes sure there's no word containing an uppercase character at the same place where the word was initially matched.

@DanielFGray 
> And roman numerals should stay upper case.
The previous concat should fix this, but if you also want to preserve roman numerals written in lowercase, like `xiv` for example, you would have to add yet another concat:

      let WORD_PATTERN = '\v%([ivxlcdm]+>)@!&%(\k*\u\k+|\k+\u\k*)@!&''@<!&<(\k)(\k{3,})>'

The `%([ivxlcdm]+>)@!&` part makes sure that there's no word written exclusively with one of the characters `ivxlcdm` (which seem to be the only ones allowed in a roman number according to wikipedia).

@toomey8 

> Seems like your would also not want to titlecase CamelCase and function.calls.

`CamelCase` should be fixed in the 2nd version of the pattern, but to prevent `function.calls` to be capitalized, you would have to add yet another concat:

    let WORD_PATTERN = '\v\.@<!\k+>\.@!&%([ivxlcdm]+>)@!&%(\k*\u\k+|\k+\u\k*)@!&''@<!&<(\k)(\k{3,})>'

The `\.@<!\k+>\.@!` part makes sure that there's not a word preceded or followed by a dot at the same position where the initial match was found.

> Never capitalize thoughtbot

It could be done by adding a last concat:

    let WORD_PATTERN = '\v%(thoughtbot)@!.&\.@<!\k+>\.@!&%([ivxlcdm]+>)@!&%(\k*\u\k+|\k+\u\k*)@!&''@<!&<(\k)(\k{3,})>'

The `%(thoughtbot)@!.&` part makes sure that `thoughtbot` can't be matched at the same position where the initial match was found.

**Comment by derBingle** [comment]
**+1 for this!**

The usefulness of this plugin would be exponential increased with this, especially for articles (the, a, an).

**Comment by GHPS** [comment]
Sure, proper titlecasing is a great idea - but no need to reinvent the wheel here...

The Python package 'python-titlecase' by Pat Pannuto handles the job really well:
https://github.com/ppannuto/python-titlecase

After installation you'll get the package plus a shell command 'titlecase'
which can be directly used as a VIM filter: !!titlecase

Features
- Adapts the New York Times Manual of Style
- Can be customized
- Maintained 

Problems
- No support for Non-ASCII characters (which this plugin has!)

**Comment by christoomey** [comment]
@GHPS thanks for sharing. I'm cautious about having vim plugins depend on external dependencies, but I'll keep this is mind if I ever get around to implementing anything on this front.

**Comment by nickjj** [comment]
I'd really like to see this. Especially adhering to Chicago or NY Time's style guides.

This site has a very very robust title converter and also lists out all of the rules: https://titlecaseconverter.com/

It is the most accurate and complete solution I've found, and I looked around a lot for this.

You could probably reverse engineer this as a no dependency plugin. I'm still super new to Vim so this is way out of my league still, but converting titles is something I do many times a day.

**Comment by huyz** [comment]
can this be closed since #13 is merged in?

**Comment by nickjj** [comment]
It depends on if you want grammatically correct titles, #13 uses https://github.com/gouch/to-title-case/blob/master/to-title-case.js which is much different than adhering to a language style guide. #13 avoids capitalizing a few "small words", personally I would stick with using https://titlecaseconverter.com/.

**Comment by huyz** [comment]
@nickjj https://titlecaseconverter.com/ is great. Thanks for repeating the link.  Even handles weird foreign languages.
