### ISSUE TITLE
No function with non-ascii characters

### ISSUE THREAD

**Issue by GHPS** [christoomey/vim-titlecase#4]
Great plugin!

It works perfectly with standard ASCII, English characters:
gT converts "apples and carrots" to "Apples And Carrots".

Unfortunately it fails with international characters:
gT converts "äpfel und möhren" to "äpfel Und möhren", not
"Äpfel Und Möhren"

It would be great if this problem could be fixed.

**Comment by christoomey** [comment]
Hey @GHPS, thanks!

Taking a quick look, the issue seems to come from the [regex used to target the word characters](https://github.com/christoomey/vim-titlecase/blob/a730d6f240c97a22a18c96767c39a89a744e662f/plugin/titlecase.vim#L13), `'\<\(\w\)\(\w*\)\>'`. Currently this is using `\w` to target "word-characters", but that is not finding non-ascii as you've highlighted.

I don't think there is a builtin regex class that will cover what we need here, but we can likely define something. Also would need to make sure vim can upcase non-ascii letters as I'm leaning on it to do that (in the substitute with the `\u` and `\L` substitution modifiers.

I don't expect I'll have much time in the near future to dig into this, but I'd be happy to review a PR if you wanted to take a shot.

**Comment by GHPS** [comment]
> Also would need to make sure vim can upcase non-ascii letters as I'm leaning on it to do that 

Just a quick test with "öäü": ~ converts it (step by step) correctly to "ÖÄÜ". VIM seemingly supports foreign characters.

And the test gives a second result:
`Error executing "function <SNR>12_titlecase":
Line   17:
E486: Pattern not found: \<\(\w\)\(\w*\)\>
`
> Taking a quick look, the issue seems to come from the regex used to target the word characters

Perfect - that's the core of the problem. The regex engine doesn't think that anything starting with a foreign character (like "äpfel") or containing such letter (like "apfelblüte") is a word.

In this case the bug is more serious and not limited to the titlecase plugin.

**Comment by GHPS** [comment]
Well - the solution is amazingly simple (but took an extensive tour through vim, regex, bless, utf-8, search encoding and iskeyword):

If \w is replaced by \k everything is fine.

Background: Keywords are defined correctly in VIM (i.e. taking foreign characters into account) 
therefore it is necessary to search for keywords in non-ASCII documents.

Please check if this patch works for you and apply it to the source...
